name: 🚀 Create Issue Branch

on:
  issues:
    types: [ opened, assigned ]
  # # The issue_comment.created event below is only needed for the ChatOps mode.
  # issue_comment:
  #   types: [ created ]
  # # The pull_request events below are only needed for pull-request related features.
  # pull_request:
  #   types: [ opened, closed ]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
