name: 🚀 Create Issue Branch

on:
    issues:
        types: [assigned]
    issue_comment:
        types: [created]

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@v1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
